---
- name : Update the System
  shell: sudo apt-get update
  become: true

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - sqlite3
  become: true

- name: Add Docker's official GPG key
  shell: "{{ item }}"
  with_items:
    - sudo install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/raspbian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - sudo chmod a+r /etc/apt/keyrings/docker.gpg
  become: true

- name: Setup repository
  shell: "{{ item }}"
  with_items:
    - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
  become: true

- name : Update the System again
  shell: sudo apt-get update
  become: true

- name: Sleep to finish previous operation and release the lock on system files 
  pause:
    minutes: 1 

- name: Install Docker Engine
  shell: sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  become: true

- name: Install Docker compose
  shell: '{{ item }}'
  with_items:
    - sudo apt-get install -y libffi-dev libssl-dev
    - sudo apt install -y python3-dev
    - sudo apt-get install -y python3 python3-pip
    - sudo pip3 install docker-compose
  become: true

- name: Give User Permission to access docker
  shell: sudo usermod -aG docker '{{ user }}'